# CI de Nìvel 01 - Disparo manual a partir de 1 clique

# nome que vai aparecer lá nas opções de pipe
name: 'Execução Integrado'

# regras de disparo da excucao (triggers)
# gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Padronizacao de codigo (Lint)
        run: yarn lint

  unit:
    runs-on: ubuntu-latest
    needs: [inspection]

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Testes de Unidade
        run: yarn run test

  # descricao do jovo
  e2e-tests:
    # maquina que o job vai executar
    runs-on: ['ubuntu-latest']
    needs: [unit]

    # passo a passo das acoes do job

    # - uses: actions/setup-node@v4
    #    with:
    #      node-version: lts/*
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Subir aplicacao local
        run: yarn start &

      - name: Testes E2E (end-to-end)
        run: yarn run e2e
        env:
          URL: 'http://localhost:3000'

      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report

  deploy:
    runs-on: ubuntu-latest
    needs: [e2e-tests]

    steps:
      - name: Deploy
        run: echo "step deploy"
